update unit tests

diff --git a/.github/workflows/continuous-integration-conda.yml b/.github/workflows/continuous-integration-conda.yml
--- a/.github/workflows/continuous-integration-conda.yml
+++ b/.github/workflows/continuous-integration-conda.yml
@@ -1,39 +1,75 @@
-name: mdet-lsst-sims
+name: tests
 
 on:
-    push:
-        branches: [ master ]
-    pull_request:
-        branches: [ master ]
+      push:
+          branches:
+              - master
+      pull_request: null
 
 jobs:
-    build:
-        runs-on: 'ubuntu-latest'
-        container: beckermr/stackvana
+    tests:
+      name: tests
+      strategy:
+          matrix:
+            pyver: [3.8]
 
-        steps:
+      runs-on: "ubuntu-latest"
 
-            - name: Install special dependencies with conda and pip
-              shell: bash -l {0}
-              run: |
-                  . /usr/local/share/stackvana-activate.sh
-                  conda install -q -y ngmix meds
+      steps:
+          - uses: actions/checkout@v2
+
+          - uses: conda-incubator/setup-miniconda@v2
+            with:
+                python-version: ${{ matrix.pyver }}
+                channels: conda-forge
+                channel-priority: strict
+                show-channel-urls: true
+
+          - name: Install special dependencies with conda and pip
+            shell: bash -l {0}
+            run: |
+                conda config --set always_yes yes
+                conda install -q mamba
+
+                mamba install -q stackvana=0
+                
+                mamba install -q \
+                  flake8 \
+                  pytest \
+                  numpy \
+                  galsim \
+                  numba \
+                  ngmix \
+                  lsstdesc-weaklensingdeblending \
+                  fitsio
+
                   pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git
                   pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git
                   pip install --no-deps git+https://github.com/esheldon/metadetect.git
 
-            - name: Checkout code
-              uses: actions/checkout@v2
+                  git clone --branch u/erykoff/onlinecoadd https://github.com/lsst/pipe_tasks.git /tmp/pipe_tasks
 
-            - name: Lint with flake8
-              shell: bash -l {0}
-              run: |
-                  . /usr/local/share/stackvana-activate.sh
-                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-                  flake8 . --count --exit-zero --max-line-length=79 --statistics
+          - name: run scons on pipe_tasks
+            shell: bash -l {0}
+            run: |
+                env
+                
+                setup -j -r /tmp/pipe_tasks
 
-            - name: Run pytest
-              shell: bash -l {0}
-              run: |
-                  . /usr/local/share/stackvana-activate.sh
-                  pytest -vv
+                pushd /tmp/pipe_tasks
+                # this might partly fail but that's ok
+                scons || echo "ok scons fails"
+                popd
+
+                pip install --no-deps -e .
+
+          - name: Lint with flake8
+            shell: bash -l {0}
+            run: |
+                flake8
+
+          - name: Run pytest
+            shell: bash -l {0}
+            run: |
+                setup -j -r /tmp/pipe_tasks
+                pytest -vv
